version_selector: true
title_switch: true
versions_file: docs/versions/versions.json
versions:
  - 2.0.0
  - 1.5.0
  - 1.4.0
  - 1.3.2
  - 1.2.2
  - 1.2.1
  - 1.2.0
  - 1.1.0
  - 1.0.0
  - 0.4.0
  - 0.3.4
  - 0.3.3
  - 0.3.2
  - latest
aliases:
  latest: 2.0.0