repos:
-   repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        require_serial: true
        language: system
        types: [ python ]
      - id: ruff
        name: ruff
        entry: uv run ruff check --force-exclude
        require_serial: true
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: uv run mypy guard
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
      - id: vulture
        name: vulture
        entry: uv run vulture vulture_whitelist.py
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
      - id: bandit
        name: bandit
        entry: uv run bandit -r guard -ll -f json -o /dev/null || uv run bandit -r guard -ll
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
      - id: safety
        name: safety
        entry: uv run safety check --json --short-report || uv run safety check
        require_serial: true
        language: system
        pass_filenames: false
      - id: pip-audit
        name: pip-audit
        entry: uv run pip-audit
        require_serial: true
        language: system
        pass_filenames: false
      - id: radon-cc
        name: radon-cyclomatic-complexity
        entry: uv run radon cc guard -nc
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
      - id: xenon
        name: xenon
        entry: uv run xenon guard --max-absolute B --max-modules A --max-average A
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
      - id: interrogate
        name: interrogate
        entry: uv run interrogate guard --fail-under 80
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
      - id: deptry
        name: deptry
        entry: uv run deptry .
        require_serial: true
        language: system
        pass_filenames: false
      - id: semgrep
        name: semgrep
        entry: uv run semgrep --config=auto --error guard
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false