name: CodeQL

on:
  push:
    branches: [master]
    paths:
      - 'compose.yml'
      - 'data/**'
      - 'Dockerfile'
      - 'examples/**'
      - 'guard/**'
      - 'mypy.ini'
      - '.pre-commit-config.yaml'
      - 'pyproject.toml'
      - 'pytest.ini'
      - 'reqs.pip'
      - 'tests/**'
  pull_request:
    branches: [master]
    paths:
      - 'compose.yml'
      - 'data/**'
      - 'Dockerfile'
      - 'examples/**'
      - 'guard/**'
      - 'mypy.ini'
      - '.pre-commit-config.yaml'
      - 'pyproject.toml'
      - 'pytest.ini'
      - 'reqs.pip'
      - 'tests/**'
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        language: [python]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

