name: Publish Containerized Demo

on:
  release:
    types: [created]
  push:
    branches:
      - master
    paths:
      - 'examples/**'
      - '.github/workflows/container-release.yml'
  workflow_dispatch:

jobs:
  publish-container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set version tag
        id: set_version
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
            echo "IS_RELEASE=true" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
            echo "IS_RELEASE=false" >> $GITHUB_ENV
          fi

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.10'

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2
        with:
          version: latest

      - name: Build with Docker Compose
        working-directory: ./examples/advanced_app
        run: |
          docker compose build

      - name: List Docker images
        run: |
          echo "Available Docker images:"
          docker images

      - name: Tag and Push to GHCR
        run: |
          IMAGE_NAME=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "fastapi-guard-example" | head -n 1)
          echo "Using image: ${IMAGE_NAME}"

          docker tag ${IMAGE_NAME} ghcr.io/${{ github.repository_owner }}/fastapi-guard-example:latest
          docker push ghcr.io/${{ github.repository_owner }}/fastapi-guard-example:latest

          if [[ "${{ env.IS_RELEASE }}" == "true" ]]; then
            docker tag ${IMAGE_NAME} ghcr.io/${{ github.repository_owner }}/fastapi-guard-example:${{ env.VERSION }}
            docker push ghcr.io/${{ github.repository_owner }}/fastapi-guard-example:${{ env.VERSION }}
          fi

